### ISSUE TITLE
support swagger 2.0 vendor extensions

### ISSUE THREAD

**Issue by borisirota** [wcandillon/swagger-js-codegen#38]
Hi,

Swagger 2.0 spec support [vendor extensions](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#vendorExtensions).

I'm using Apigee's [x-swagger-router-controller](https://github.com/apigee-127/a127-documentation/wiki/Quick-start-deep-dive#the-paths-object-and-swagger-extensions) and the code fails (make sense):
```
TypeError: Cannot call method 'forEach' of undefined
    at /node_modules/swagger-js-codegen/lib/codegen.js:56:27
    at forOwn (/node_modules/swagger-js-codegen/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/node_modules/swagger-js-codegen/node_modules/lodash/dist/lodash.js:3302:9)
    at /node_modules/swagger-js-codegen/lib/codegen.js:45:11
    at forOwn (/node_modules/swagger-js-codegen/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/node_modules/swagger-js-codegen/node_modules/lodash/dist/lodash.js:3302:9)
    at getViewForSwagger2 (/node_modules/swagger-js-codegen/lib/codegen.js:43:7)
    at getCode (/node_modules/swagger-js-codegen/lib/codegen.js:131:49)
    at Object.exports.CodeGen.getNodeCode (/node_modules/swagger-js-codegen/lib/codegen.js:169:16)
    at Object.<anonymous> (/test.js:6:32)
```

Swagger.yaml example:
```
  /users:
    x-swagger-router-controller: usersCtrl
    post:
      summary: Add user
      description: Add user
      operationId: add
      parameters:
        -
          name: user
          in: body
          description: user's object
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: New user created
          headers:
            Location: 
              description: New user id
              type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      summary: Delete user
      description: Delete user
      operationId: delete
      responses:
        204:
          description: User deleted
        404:
          description: User not found
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:

  User:
    required:
      - userName
      - password
      - email
    properties: 
      userName: 
        type: string
      password: 
        type: string
      email: 
        type: string

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
```

Thanks,
Boris

**Comment by borisirota** [comment]
Just to be clear, by support my meaning is to ignore vendor extensions without crushing :)

**Comment by wcandillon** [comment]
@borisirota Thank you so much for reporting this. I'm on it.

**Comment by wcandillon** [comment]
@borisirota It looks that this is fixed in the latest version of the package. Are you using the latest version of the package?

**Comment by wcandillon** [comment]
@borisirota nevermind, I am able to reproduce it, working on a fix now.
