### ISSUE TITLE
Minimum swagger json gives TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by OwenBrotherwood** [wcandillon/swagger-js-codegen#67]
For some reason, a minimum json (from Swagger Editor) gives TypeError: Cannot read property 'toUpperCase' of undefined

cat test.js
-------------
var fs = require('fs');
var CodeGen = require('swagger-js-codegen').CodeGen;

var file = 'swagger/min.json';
var swagger = JSON.parse(fs.readFileSync(file, 'UTF-8'));
var angularjsSourceCode = CodeGen.getAngularCode({ className: 'Test', swagger: swagger });
console.log(angularjsSourceCode);

cat swagger/min.json
-----------------------------
{
  "swagger" : "2.0",
  "info" : {
    "version" : "0.0.0",
    "title" : "Simple API"
  },
  "paths" : {
    "/" : {
      "get" : {
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        }
      }
    }
  }
}

node test.js
----------------
/home/ob/node_modules/swagger-js-codegen/lib/codegen.js:33
    return m.toLowerCase() + result[0].toUpperCase() + result.substring(1);
                                      ^
TypeError: Cannot read property 'toUpperCase' of undefined
    at getPathToMethodName (/home/ob/node_modules/swagger-js-codegen/lib/codegen.js:33:39)
    at /home/ob/node_modules/swagger-js-codegen/lib/codegen.js:63:130
    at forOwn (/home/ob/node_modules/swagger-js-codegen/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/home/ob/node_modules/swagger-js-codegen/node_modules/lodash/dist/lodash.js:3302:9)
    at /home/ob/node_modules/swagger-js-codegen/lib/codegen.js:56:11
    at forOwn (/home/ob/node_modules/swagger-js-codegen/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/home/ob/node_modules/swagger-js-codegen/node_modules/lodash/dist/lodash.js:3302:9)
    at getViewForSwagger2 (/home/ob/node_modules/swagger-js-codegen/lib/codegen.js:49:7)
    at getCode (/home/ob/node_modules/swagger-js-codegen/lib/codegen.js:159:49)
    at Object.exports.CodeGen.getAngularCode (/home/ob/node_modules/swagger-js-codegen/lib/codegen.js:194:16)

**Comment by wcandillon** [comment]
thks for reporting this. I proposed a fix for merging.
